log-level: "error"        # error|warn|info|debug
log-dest: "stderr"       # stderr|stdout|file

ca-server-url: "https://ca.example.test"
client-id: "example-client-id"
client-secret: "example-client-secret"
token-url: "https://idp.example.test/oauth/token"

user:
  key: "testdata/id.pub"
  principal:
    - alice
    - devops
  duration: 3600

host:
  key: "testdata/id.pub"
  principal:
    - ip-10-0-1-23.ec2.internal
    - web
  duration: 3600

