name: generic-go-versionbuild

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      artifactVersion:
        required: true
        type: string
      sha:
        required: false
        type: string
        default: ${{ github.sha }}

jobs:

  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./${{ inputs.service }}

    steps:
      - name: checkout sources
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}

      - name: setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ inputs.service }}/go.mod
          cache: true
          cache-dependency-path: |
            ${{ inputs.service }}/go.sum
            ${{ inputs.service }}/go.mod

      - name: install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.5.0
          golangci-lint version

      - name: run lint
        run: make lint

  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./${{ inputs.service }}

    steps:
      - name: checkout sources
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}

      - name: setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ inputs.service }}/go.mod
          cache: true
          cache-dependency-path: |
            ${{ inputs.service }}/go.sum
            ${{ inputs.service }}/go.mod

      - name: run tests
        run: make test

  publish-artifact-name:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./${{ inputs.service }}

    outputs:
      artifact_name: ${{ steps.artifact-name.outputs.name }}

    steps:
      - name: checkout sources
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}

      - name: get artifact name
        id: artifact-name
        run: echo "name=$(make getname VERSION=${{ inputs.artifactVersion }})" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest

    needs:
      - lint
      - test
      - publish-artifact-name

    strategy:
      matrix:
        go-version:
          - '1.24'
          - '1.25'
        include:
          - go-version: '1.25'
            upload: true

    defaults:
      run:
        working-directory: ./${{ inputs.service }}

    steps:
      - name: checkout sources
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}

      - name: setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: |
            ${{ inputs.service }}/go.sum
            ${{ inputs.service }}/go.mod

      - name: build
        run: make build VERSION="${{ inputs.artifactVersion }}"

      - name: upload build artifact
        if: matrix.upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.publish-artifact-name.outputs.artifact_name }}
          path: ${{ inputs.service}}/bin/${{ steps.artifact-name.outputs.name }}
          retention-days: 5

  create-linux-packages:
    needs:
      - build
      - publish-artifact-name

    runs-on: ubuntu-latest

    steps:
      - name: install nfpm
        run: |
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
          sudo apt update
          sudo apt install -y nfpm

      - name: checkout sources
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}

      - name: download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.publish-artifact-name.outputs.artifact_name }}
          path: ${{ inputs.service }}/bin
          merge-multiple: true

      - name: package with nfpm
        run: |
          mkdir -p dist
          nfpm pkg --packager archlinux --config nfpm.yaml --target dist/
          nfpm pkg --packager deb --config nfpm.yaml --target dist/

      - name: upload build artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/*
          retention-days: 5
