name: generic-go-versionbuild

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      artifactVersion:
        required: true
        type: string
      sha:
        required: false
        type: string
        default: ${{ github.sha }}
        
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - '1.22'
          - '1.23'
          - '1.24'
          - '1.25'
        include:
          - go-version: '1.25'
            upload: true
    defaults:
      run:
        working-directory: ./${{ inputs.service }}
         
    steps:
      - name: checkout sources
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}

      - name: setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: test
        run: make test

      - name: build
        run: make build VERSION="${{ inputs.artifactVersion }}"

      - name: get artifact name
        if: matrix.upload
        id: artifact-name
        run: echo "name=$(make getname VERSION=${{ inputs.artifactVersion }})" >> $GITHUB_OUTPUT

      - name: upload build artifact
        if: matrix.upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact-name.outputs.name }}
          path: ${{ inputs.service}}/bin/${{ steps.artifact-name.outputs.name }}
          retention-days: 5
