name: create and publish docker container

on:
  push:
    branches: [ '*' ]
    paths:
      - server/ssh-key-signer-server/**
      - .github/workflows/ssh-key-signer-server-docker.yml
  workflow_call:
    inputs:
      sha:
        required: false
        type: string
        default: ${{ github.sha }}
env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}
  PROJECT: ssh-key-signer-server
  PROJECT_DIR: ./server

jobs:
  build:
    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}

    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}

      - name: "display sha"
        run: |
          echo "found sha ${{ inputs.sha }}"

      - name: set up jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: build with maven
        run: mvn clean package --projects ${{ env.PROJECT }} --also-make --batch-mode -Pproduction

      - name: extract project version
        id: extract_version
        run: |
          echo "MAVEN_NAME=$(mvn help:evaluate -Dexpression=project.artifactId --projects ${{ env.PROJECT }} -q -DforceStdout)" >> $GITHUB_OUTPUT
          echo "MAVEN_VERSION=$(mvn help:evaluate -Dexpression=project.version --projects ${{ env.PROJECT }} -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: extract docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=raw,value=${{ steps.extract_version.outputs.MAVEN_VERSION }}

      - name: build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.PROJECT_DIR }}/${{ env.PROJECT }}
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            APP_NAME=${{ steps.extract_version.outputs.MAVEN_NAME }}
            APP_VERSION=${{ steps.extract_version.outputs.MAVEN_VERSION }}

      # the following steps uses the identity token to provision an ephemeral certificate
      # against the sigstore community Fulcio instance.`

      - name: install Cosign
        if: startsWith(github.ref, 'refs/tags/v')
        uses: sigstore/cosign-installer@v3.8.1

      - name: write cosign key to file
        if: startsWith(github.ref, 'refs/tags/v')
        run: 'echo "$KEY" > cosign.key'
        shell: bash
        env:
          KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: sign the published docker image
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: |
          echo "${TAGS}" | while read tag; do
            cosign sign --key cosign.key --yes $tag
          done
